name: Check Lint/Format

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
    types: [opened, reopened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Base Initialization
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm i

      # Real Jobs
      - name: Say Hi
        run: echo "Hello Boï!"
      - name: Run Biome Lint Check
        run: npx @biomejs/biome check .
