name: Check Lint/Format

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
    types: [opened, reopened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Base Initialization
      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm i

      # Real Jobs
      - name: Say Hi
        run: echo "Hello Boï!"
      - name: Run Biome Lint Check
        run: npx @biomejs/biome check .
