name: Check Lint/Format

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Base Initialization
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci

      # Real Jobs
      - name: Run Biome Lint Check
        run: npx @biomejs/biome check .
