name: Front

on:
  pull_request:
    branches:
      - dev
      - master
      - main
    types: [opened, reopened, synchronize]
    paths:
      - 'web-app/**'
      - '.github/workflows/webapp-test:unit.yaml'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Base Initialization
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci

      # Real Jobs
      - name: Run tests
        working-directory: ./web-app/
        run: npm ci && npm run test

  tba:
    runs-on: ubuntu-latest
    steps:
      # Base Initialization
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci

      # Real Jobs
      - name: Run tests
        working-directory: ./e2e/
        run: npm ci && npm run test
